#!/bin/bash
#set -x
confirm=false

menu() {
   # prompt user until disk has been confirmed
   while [ $confirm = false ]; do
      # create a list of disks
      disks=()
      while read -r type ro name; do
      [[ $type == disk && $ro == 0 ]] || continue
         printf -v name %b "$name"
         disks+=("$name")
      done < <(lsblk -rnotype,ro,kname)

      # print that list of disks
      for i in "${!disks[@]}"; do
         printf "%s) %s\\n" "$i" "${disks[$i]}"
      done

      # prompt for selection
      read -rp "Which disk would you like to install to? " opt
      # test
      if [[ $opt =~ ^[0-9]+$ ]] && ((opt=10#$opt, opt >= 0 && opt < ${#disks[@]})); then
         echo "REALLY SURE you want to install to ${disks[opt]}?"
	 while read -r -p "yes/no: " yn; do
            case ${yn,,} in
               y|yes) yn=yes; confirm=true; break;;
	       n|no) yn=no; break;;
	       *) printf >&2 "Please answer yes or no.\\n";;
            esac
         done
      echo "Installing to ${disks[opt]}"
      else
         printf 'Invalid selection.\n'
      fi
   done
}

menu
