#!/bin/bash

disks=()
while read -r type ro name
do [[ $type == disk && $ro == 0 ]] || continue
	printf -v name %b "$name"
	disks+=("$name")
done < <(lsblk -rnotype,ro,kname)

for i in "${!disks[@]}"; do
	    printf "%s) %s\n" "$i" "${disks[$i]}"
done
printf 'Select drive from the above list: '
IFS= read -r opt
if [[ $opt =~ ^[0-9]+$ ]] && (( (opt >= 0) && (opt <= "${#disks[@]}") )); then
    echo "Install to ${disks[opt]}?"
else
    printf 'Invalid selection.\n'
fi
